# Generated by Django 4.0.4 on 2022-11-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial_predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fase_desc',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
