# Generated by Django 4.0.4 on 2022-11-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundial_predict', '0002_partido_fase_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='equipo1',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='mundial_predict.seleccion'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo2',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='mundial_predict.seleccion'),
        ),
    ]
