# Generated by Django 4.0.4 on 2022-11-16 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundial_predict', '0004_alter_partido_equipo1_alter_partido_equipo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id_prediccion', models.AutoField(primary_key=True, serialize=False)),
                ('goles', models.IntegerField(blank=True, default=None, max_length=2, null=True)),
                ('puntos', models.IntegerField(blank=True, default=None, max_length=1, null=True)),
                ('codigo_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundial_predict.partido')),
                ('codigo_seleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundial_predict.seleccion')),
            ],
        ),
    ]
