# Generated by Django 4.0.4 on 2022-11-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial_predict', '0005_prediccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='goles',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='puntos',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
